spring:
  application:
    name: spring-boot-auth-server
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/spring-boot-auth-server}
    username: ${DATASOURCE_USERNAME:spring-boot-auth-server}
    password: ${DATASOURCE_PASSWORD:spring-boot-auth-server}
  flyway:
    enabled: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
  security:
    oauth2:
      authorizationserver:
        issuer: ${AUTH_SERVER_ISSUER_URI:https://spring-boot-auth-server:9000}

server:
  port: 9000
  ssl:
    certificate: "file:/certs/cert.pem"
    certificate-private-key: "file:/certs/key.pem"

oauth:
  client:
    registrations:
      web-bff:
        client-id: "spring-boot-web-bff"
        client-secret: "${WEB_BFF_CLIENT_SECRET}"
        redirect-uris:
          - "https://localhost:8080/login/oauth2/code/auth-server"
          - "https://spring-boot-web-bff:8080/login/oauth2/code/auth-server"
        post-logout-redirect-uris:
          - "https://localhost/"
          - "https://angular-ui-web/"
        scopes:
          - "openid"
          - "profile"
          - "email"
        access-token-time-to-live: 5m
        refresh-token-time-to-live: 24h
        authorization-code-time-to-live: 5m
        require-proof-key: true
        require-authorization-consent: false
      mobile-bff:
        client-id: "spring-boot-mobile-bff"
        client-secret: "${MOBILE_BFF_CLIENT_SECRET}"
        redirect-uris:
          - "https://localhost:8082/login/oauth2/code/auth-server"
          - "https://spring-boot-mobile-bff:8082/login/oauth2/code/auth-server"
        post-logout-redirect-uris:
          - "myapp:/"
        scopes:
          - "openid"
          - "profile"
          - "email"
        access-token-time-to-live: 5m
        refresh-token-time-to-live: 24h
        authorization-code-time-to-live: 5m
        require-proof-key: true
        require-authorization-consent: false
